name: Build Docker image


on: [push]

permissions:
  id-token: write
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v3
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::677293677370:role/GithubAccessRole
          role-session-name: OIDCSession

      - run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 677293677370.dkr.ecr.us-east-1.amazonaws.com
          docker build -t modamod/flask-docker .
          docker tag modamod/flask-docker:latest 677293677370.dkr.ecr.us-east-1.amazonaws.com/modamod/flask-docker:latest
          docker push 677293677370.dkr.ecr.us-east-1.amazonaws.com/modamod/flask-docker:latest
        working-directory: ./docker


        shell: bash
